name: Un Saludo desde Actions

on:
  push:
    branches: [ main ]

jobs:
  saludar-al-usuario:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Imprimir saludo
        run: echo "¡Hola, ${{ github.actor }}! Gracias por hacer push."

      - name: Listar archivos en el runner
        run: ls -la
    
